# Producer Node Config file.
agent-name = <PRODUCER_NAME>                                # Can be anything you want will show up in nodeop log good practice WireNetwork-Producer

plugin = sysio::producer_api_plugin
plugin = sysio::producer_plugin
plugin = sysio::chain_plugin
plugin = sysio::net_plugin
plugin = sysio::db_size_api_plugin                         # Optional, provides API to query db size

# HTTP Plugin
http-server-address = 0.0.0.0:8887                         # This should never be made publicly accessible
http-max-response-time-ms = 100                            # Maximum time in milliseconds to wait for a response before returning an error
http-validate-host = false
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept

# Producer Plugin 
chain-threads = 8
net-threads = 8                                             # Could be useful to increase on a relay node. 
producer-name = <PRODUCER_NAME>                             # Account name you have registered as a producer with
enable-stale-production = false                             # Enable block production, even if the chain is stale, if booting as genesis node must be set to true
pause-on-startup = false                                    # Start this node in a state where production is paused
signature-provider = signing-key,wire,wire,<SIGNING_PUB_KEY>,KEY:<SIGNING_PRIV_KEY>
signature-provider = finalizer-key,wire,wire_bls,<FINALIZER_PUB_KEY>,KEY:<FINALIZER_PRIV_KEY>

# Chain Plugin
abi-serializer-max-time-ms = 1000                           # Override default value of 15000 in micro
chain-state-db-size-mb = 2048                               # Size of the chain state database in MB, should match the max RAM of the chain you are running. 
chain-state-db-guard-size-mb = 1024                         # Size of the chain state database guard in MB. will cleanly shut down if you reach this remaining size.
database-map-mode = heap                                    # Big trade offs on start up / shut down time when chain state starts to grow. Testnets: suggested "mapped_private", Mainnet: "heap" Options: "heap", "mapped", "mapped_private", " locked" Note: Mapped does heavy writes, not good for SSDS.
sys-vm-oc-compile-threads = 4

# Net Plugin
p2p-listen-endpoint = 0.0.0.0:4443
p2p-server-address = <SERVER_IP>:4443
p2p-max-nodes-per-host = 5
max-clients = 5

# Peer List
p2p-peer-address=127.0.0.1:4442 # Connection to BP-Relay Node(s) need 1 entry per BP-Relay Node, replace 4442 with the correct port for each BP-Relay Node
