# Chain API Node Example Config
agent-name = <PRODUCER_NAME>                            # Can be anything you want will show up in nodeop log good practice WireNetwork-API

plugin = sysio::http_plugin
plugin = sysio::chain_api_plugin
plugin = sysio::chain_plugin
plugin = sysio::net_plugin

chain-threads = 8
net-threads = 8
http-threads = 8
read-only-threads = 3                                   # Not on main thread
read-only-write-window-time-us = 200000                 # These can be tweaked if you want your API node to facilitate both.
read-only-read-window-time-us = 60000

# HTTP Plugin ( Publicly accessible )
http-server-address = 0.0.0.0:8888
http-validate-host = false
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
http-max-response-time-ms = 100
abi-serializer-max-time-ms = 1000
verbose-http-errors = true

# Chain Plugin
wasm-runtime = sys-vm-jit
sys-vm-oc-compile-threads = 4
chain-state-db-size-mb = 2048                               # Size of the chain state database in MB, should match the max RAM of the chain you are running.
database-map-mode = heap                        # Big trade offs on start up / shut down time when chain state starts to grow. Testnets: suggested "mapped_private", Mainnet: "heap" Options: "heap", "mapped", "mapped_private", " locked" Note: Mapped does heavy writes, not good for SSDS.
block-log-retain-blocks = 10000                           # Number of blocks to retain in block log, 0 for all blocks
contracts-console = true
trusted-producer = <PRODUCER_NAME>                        # Trusted producer for chain API, should be the same as the producer name in the block producer config. THIS CANNOT BE USED IF WE ARE USING STATIC PRODUCER ACCOUNTS.
enable-account-queries = true
transaction-retry-max-storage-size-gb = 5
transaction-finality-status-max-storage-size-gb = 5

# Net Plugin ( Don't want this publicly accessible )
p2p-listen-endpoint = 0.0.0.0:4444
p2p-server-address = <SERVER_IP>:4444
p2p-max-nodes-per-host = 5
p2p-accept-transactions = false                            # Huge performance increase when disabled.
max-clients = 5

# Peer List
p2p-peer-address=127.0.0.1:4442 # Connection to BP-Relay Node(s) need 1 entry per BP-Relay Node, replace 4442 with the correct port for each BP-Relay Node
