# BP-Relay Node Example Config
agent-name = <PRODUCER_NAME>                        # Can be anything you want will show up in nodeop log good practice WireNetwork-bp-relay 

plugin = sysio::http_plugin
plugin = sysio::chain_api_plugin
plugin = sysio::chain_plugin
plugin = sysio::net_plugin

chain-threads = 8
net-threads = 8

# HTTP Plugin ( Not publicly accessible )
http-server-address = 0.0.0.0:8886
http-validate-host = false
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
http-max-response-time-ms = 100
abi-serializer-max-time-ms = 1000
verbose-http-errors = true
api-accept-transactions = false

# Chain Plugin
wasm-runtime = sys-vm-jit
sys-vm-oc-enable = 1                                # Enable optimized compilation in WASM, only want this enabled on BP-Relay Nodes
sys-vm-oc-compile-threads = 4
chain-state-db-size-mb = 2048                               # Size of the chain state database in MB, should match the max RAM of the chain you are running.
database-map-mode = heap                  # Big trade offs on start up / shut down time when chain state starts to grow. Testnets: suggested "mapped_private", Mainnet: "heap" Options: "heap", "mapped", "mapped_private", " locked" Note: Mapped does heavy writes, not good for SSDS.
trusted-producer = <PRODUCER_NAME>                  # Account name you have registered as a producer with. SHOULD ONLY BE USED IF THIS IS YOUR PRODUCING NODE.

# Net Plugin ( Not Publicly accessible ) bp-relay nodes and your personal ext-relay will sync with this
p2p-listen-endpoint = 0.0.0.0:4442
p2p-server-address = <SERVER_IP>:4442
p2p-max-nodes-per-host = 5
max-clients = 5

# Peer List - You want this to connect to other producer BP-Relay nodes and your producer node.Ideally you have previous and next bp-relay relating to your position in the schedule.
p2p-peer-address=127.0.0.1:4443 # local producer node